version: '2'
volumes:
  db:
services:
  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=MySUP3Rs3cREtP@SsWorD1239856
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    links:
      - db
    volumes:
      - /appdata/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=MySUP3Rs3cREtP@SsWorD1239856
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db