version: '2'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /data/${STACK_NAME}/mariadb/data:/var/lib/mysql
    env_file:
      - .env
  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mariadb
    volumes:
      - /data/${STACK_NAME}/nextcloud/html:/var/www/html
      - /data/${STACK_NAME}/nextcloud/data:/var/www/html/data
    env_file:
      - .env